version: "3"
services:
    menu:
        container_name: menu_api
        build: ./menu
        ports:
            - "5000:5000"
        volumes:
            - ./menu:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            - menu_db
        restart: always
        environment:
            DB_URI: "postgresql://root:eatn@menu_db:5432/menu"

    menu_db:
        container_name: menu_db
        image: postgres
        volumes:
            - ./db_volumes/menu/:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: eatn
            POSTGRES_DB: menu
    
    cashier_frontend:
        container_name: cashier_frontend
        build: ./cashier_frontend
        ports:
            - "4000:4000"
        volumes:
            - ./cashier_frontend:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            # - api_gateway
            - menu
        restart: always
